// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_1KMGs8588owtgHyLz2k24yXCTrV5lo',
    appId: '1:102401967234:web:e5137eb29c8cd21ae2a09b',
    messagingSenderId: '102401967234',
    projectId: 'epicrides-457c5',
    authDomain: 'epicrides-457c5.firebaseapp.com',
    storageBucket: 'epicrides-457c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHENG65gx0OsaNNCQHFm-QTlwPON8QXbI',
    appId: '1:102401967234:android:de91952b5ac7b110e2a09b',
    messagingSenderId: '102401967234',
    projectId: 'epicrides-457c5',
    storageBucket: 'epicrides-457c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWs_5TzINmZF64wohAazaJMkDH5Nka0nw',
    appId: '1:102401967234:ios:e8ba16334d51d1e1e2a09b',
    messagingSenderId: '102401967234',
    projectId: 'epicrides-457c5',
    storageBucket: 'epicrides-457c5.appspot.com',
    iosBundleId: 'com.example.epicRides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWs_5TzINmZF64wohAazaJMkDH5Nka0nw',
    appId: '1:102401967234:ios:e8ba16334d51d1e1e2a09b',
    messagingSenderId: '102401967234',
    projectId: 'epicrides-457c5',
    storageBucket: 'epicrides-457c5.appspot.com',
    iosBundleId: 'com.example.epicRides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_1KMGs8588owtgHyLz2k24yXCTrV5lo',
    appId: '1:102401967234:web:f62d647d97436799e2a09b',
    messagingSenderId: '102401967234',
    projectId: 'epicrides-457c5',
    authDomain: 'epicrides-457c5.firebaseapp.com',
    storageBucket: 'epicrides-457c5.appspot.com',
  );
}
